  
name: v2ToClash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: composer php
      run: |
        php composer.phar require mustangostang/spyc
    - name: php
      run: |
        php v2c.php
        zip -r clash.zip clash.yaml
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: GitHub Actions V2rayToClash
        body: Build job of ${{github.repository}} completed successfully!
        to: hclasmn@qq.com
        from: GitHub Actions V2rayToClash
        attachments: ./clash.zip  
